name: lint

on:
  [push, pull_request]

jobs:
  run-linters:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: stefanoeb/eslint-action@1.0.2

  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v1
      - name: Commitsar Action
        uses: docker://aevea/commitsar
